# Numpy

In [3]:
from time import time
import numpy as np

In [4]:
x = np.random.random(100000000)

In [5]:
start = time()
sum(x) / len(x)
print(time() - start)

17.142690658569336


In [1]:
start = time()
np.mean(x)
print(time() - start)


NameError: name 'time' is not defined

# Arrays

In [27]:
a = np.array([1,2,3])
b = np.array([1.8,2,3.7], dtype = np.int64)
c = np.array([2,4,'6'], dtype = np.str)
d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [30]:
print("Array {}\nType {}\nElements Type: {}".format(d,type(d),d.dtype))
print("Dimensions: {}\nLength: {}".format(d.shape,d.size))

Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type <class 'numpy.ndarray'>
Elements Type: int64
Dimensions: (3, 3)
Length: 9


In [33]:
np.save("array1",a)
print(np.load("array1.npy"))

[1 2 3]


In [37]:
x = np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
x = np.ones((3),dtype=str)
print(x)

['1' '1' '1']


In [42]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [43]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [49]:
x = np.arange(0,30,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [58]:
x = np.linspace(0,30,16)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [60]:
x = np.reshape(x,(8,2))
print(x)

[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]
 [12. 14.]
 [16. 18.]
 [20. 22.]
 [24. 26.]
 [28. 30.]]


In [65]:
y = np.arange(1,10).reshape((3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.random.random((4,5))
print(x)

[[0.38951893 0.85804853 0.52926261 0.42344959 0.75364935]
 [0.96255818 0.11555854 0.62815418 0.68857921 0.53213529]
 [0.46976511 0.20485786 0.4095733  0.93834117 0.81597109]
 [0.53244089 0.95273622 0.93372647 0.51336485 0.2130213 ]]


In [81]:
x = np.random.randint(1,11,(5))
print(x)
print(x.max())
print(x.min())
print(x.sum())

[10  6  1  6  7]
10
1
30


In [82]:
x = np.random.normal(10,5,size=(3,3))
print(x)
print(x.mean())

[[ 8.52662224  0.67905659 15.56947477]
 [ 9.96073019  7.91619455  1.25932834]
 [10.33690266  4.44791364  6.27270824]]
7.218770135675268
