# Numpy

In [3]:
from time import time
import numpy as np

In [4]:
x = np.random.random(100000000)

In [5]:
start = time()
sum(x) / len(x)
print(time() - start)

17.142690658569336


In [2]:
start = time()
np.mean(x)
print(time() - start)


NameError: name 'x' is not defined

## Arrays

In [27]:
a = np.array([1,2,3])
b = np.array([1.8,2,3.7], dtype = np.int64)
c = np.array([2,4,'6'], dtype = np.str)
d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [30]:
print("Array {}\nType {}\nElements Type: {}".format(d,type(d),d.dtype))
print("Dimensions: {}\nLength: {}".format(d.shape,d.size))

Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type <class 'numpy.ndarray'>
Elements Type: int64
Dimensions: (3, 3)
Length: 9


In [33]:
np.save("array1",a)
print(np.load("array1.npy"))

[1 2 3]


In [37]:
x = np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
x = np.ones((3),dtype=str)
print(x)

['1' '1' '1']


In [42]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [43]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
x = np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [49]:
x = np.arange(0,30,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [58]:
x = np.linspace(0,30,16)
print(x)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [60]:
x = np.reshape(x,(8,2))
print(x)

[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]
 [12. 14.]
 [16. 18.]
 [20. 22.]
 [24. 26.]
 [28. 30.]]


In [65]:
y = np.arange(1,10).reshape((3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x = np.random.random((4,5))
print(x)

[[0.38951893 0.85804853 0.52926261 0.42344959 0.75364935]
 [0.96255818 0.11555854 0.62815418 0.68857921 0.53213529]
 [0.46976511 0.20485786 0.4095733  0.93834117 0.81597109]
 [0.53244089 0.95273622 0.93372647 0.51336485 0.2130213 ]]


In [81]:
x = np.random.randint(1,11,(5))
print(x)
print(x.max())
print(x.min())
print(x.sum())

[10  6  1  6  7]
10
1
30


In [82]:
x = np.random.normal(10,5,size=(3,3))
print(x)
print(x.mean())

[[ 8.52662224  0.67905659 15.56947477]
 [ 9.96073019  7.91619455  1.25932834]
 [10.33690266  4.44791364  6.27270824]]
7.218770135675268


In [10]:
x = np.array([[1,2],[3,4]])
print(x[0,0])

1


In [20]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X[1,1] = "20"
print(X)

[[ 1  2  3]
 [ 4 20  6]
 [ 7  8  9]]


In [25]:
x = np.arange(1,10).reshape(3,3)
print(x)
x[0,1] = 0
x[0,2] = 0
x[1,0] = 0
x[1,2] = 0
x[2,0] = 0
x[2,1] = 0
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [36]:
x = np.arange(1,10).reshape(3,3)
y = np.delete(x,[0,1],axis=1)
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]
 [9]]


In [55]:
x = [1,2,3]
x = np.append(x,4)
print(x)
x = np.linspace(1,9,9).reshape(3,3)
print(x)
y = np.append(x,[[10,11,12]],axis=0)
print(y)
z = np.append(x,[[10],[11],[12]],axis=1)
print(z)

[1 2 3 4]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
[[ 1.  2.  3. 10.]
 [ 4.  5.  6. 11.]
 [ 7.  8.  9. 12.]]


In [57]:
y = np.insert(x,2,[2.5])
print(y)
z = np.insert(x,3,[10,11,12],axis=0)
print(z)

[1.  2.  2.5 3.  4.  5.  6.  7.  8.  9. ]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [63]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.vstack((x,y))
w = np.hstack((x,y))
print(z,w)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [3]:
a = np.arange(1,17).reshape(4,4)
print(a)
print(a[1:,2:])
b = a.copy()
b = np.copy(a[2:,2:])
print(b)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 7  8]
 [11 12]
 [15 16]]
[[11 12]
 [15 16]]


In [4]:
print(np.diag(b))
print(np.diag(a,k=1))
s = np.diag([1,2,1])
print(np.unique(s))

[11 16]
[ 2  7 12]
[0 1 2]


In [19]:
X = np.arange(12).reshape(3,4)
print(X[(X>5) & (X<10)])
print(X[(X > 10) & (X < 17)])

[6 7 8 9]
[11]


In [21]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


In [2]:
x = np.random.randint(1,11,size=(10,))
print(x)
y = np.sort(x)
print(x)
x.sort()
print(x)
print(y)
print(np.sort(np.unique(x)))
a = np.random.randint(0,9,size=(4,3))
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

NameError: name 'np' is not defined

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([2,1,2,1,2])
print(np.add(a,b),a+b)
print(np.subtract(a,b),a-b)
print(np.multiply(a,b),a*b)
print(np.divide(a,b),a/b)
print(np.sqrt(a))
print(np.exp(a))
print(np.power(a,2))
print(a.sum())
print(a.mean())
print(a.std()) #axis = 0
print(a.max())
print(a.shape)
print(a.size)


[3 3 5 5 7] [3 3 5 5 7]
[-1  1  1  3  3] [-1  1  1  3  3]
[ 2  2  6  4 10] [ 2  2  6  4 10]
[0.5 2.  1.5 4.  2.5] [0.5 2.  1.5 4.  2.5]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 1  4  9 16 25]
15
3.0
1.4142135623730951
5
(5,)
5
